project:
  type: website

website:
  title: "quarto-website"
  navbar:
    logo: "static/logo.png"
    title: false
    background: primary
    right:
      - href: publications/index.qmd
        text: Publications
      - href: blog/index.qmd
        text: Blog
      - href: project/index.qmd
        text: Projects
      - href: about/index.qmd
        text: About me
  page-footer:
    left: "© 2022 Termeh Shafie"
    center: "powered by [quarto](https://quarto.org)"
    right:
      - icon: twitter
        href: https://twitter.com/termehshafie
      - icon: github
        href: https://github.com/termehs
      - text: <i class="ai ai-google-scholar" role="img"></i>
        href: https://scholar.google.de/citations?user=Si-WbhAAAAAJ&hl=en
      - text: <i class="ai ai-orcid" role="img"></i>
        href: https://orcid.org/0000-0002-8419-8477
      - text: <i class="ai ai-researchgate" role="img"></i>
        href: https://www.researchgate.net/profile/Termeh-Shafie
format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: 
      - styles.css
      - academicons.css
    toc: true
execute: 
  freeze: auto


