project:
  type: website
  
website:
  site-url: "https://golemlab.eu"
  title: "GOLEM Lab"
  favicon: "static/favicon.png"
  twitter-card:
    creator: "@fpianz"
    site: "@fpianz"
    description: "Digital Humanities research project about fanfiction and reading"
    image: "static/img/avatar.png"
    card-style: "summary"
  search: false
  open-graph: 
    site-name: GOLEM Lab
    description: "Digital Humanities research project about fanfiction and reading"
    image: "static/img/avatar.png"
  navbar:
    # logo: "static/favicon.png"
    title: false
    background: primary
    right:
      - href: about/index.qmd
        text: About
      - href: news/index.qmd
        text: News
      - href: publications/index.qmd
        text: Publications
  page-footer:
    left: "CC-BY-SA 2022"
    center: "powered by [quarto](https://quarto.org) | theme by [Termeh Shafie](http://mrs.schochastics.net)"
    right:
      - icon: mastodon
        href: https://mstdn.social/@fpianz
      - icon: twitter
        href: https://twitter.com/fpianz
      - icon: github
        href: https://github.com/GOLEM-lab
      - text: <i class="ai ai-orcid" role="img"></i>
        href: https://orcid.org/0000-0002-8419-8477

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    date-format: iso
    css: 
      - styles.css
      - academicons.css
    toc: true
    highlight-style: zenburn
execute: 
  freeze: auto

