project:
  type: website
  
website:
  site-url: "https://golemlab.eu"
  title: "GOLEM Lab"
  favicon: "static/favicon.png"
  search: false
  open-graph: 
    site-name: GOLEM Lab
    description: "Digital Humanities research project about the cultural evolution of online fiction"
    image: "static/img/avatar.png"
  navbar:
    logo: "static/logotype_oblique.png"
    title: false
    background: primary
    right:
      - href: about/index.qmd
        text: About
      - href: team/index.qmd
        text: Team
      - href: news/index.qmd
        text: News
      - href: publications/index.qmd
        text: Publications
  page-footer:
    left: CC-BY-SA 2022 <br> Powered by [quarto](https://quarto.org) <br> Theme by [Termeh Shafie](http://mrs.schochastics.net)
    right:
      - icon: mastodon
        href: https://mstdn.social/@fpianz
      - icon: github
        href: https://github.com/GOLEM-lab

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    date-format: iso
    css: 
      - styles.css
      - academicons.css
    toc: true
    highlight-style: zenburn
    include-in-header:
      - mailerlite.js
execute: 
  freeze: auto

